### ISSUE TITLE
Not able to package VsCode  Extention 

### ISSUE THREAD

**Issue by AmAnVeRmA3301** [serganch/ideals#46]
###  Invalid  extention name "rri.ideals"
**_NodeVersion_**  v18.7.0
**_Os_**  Ubuntu 22.10 (Arm)

root@kali:~/ideals/client/vscode# vsce package
 ERROR  Invalid extension name 'rri.ideals'

**Comment by haringsrob** [comment]
@AmAnVeRmA3301 you can change the name in package.json to make it work

**Comment by AmAnVeRmA3301** [comment]
@haringsrob  Thanks it worked !
