### ISSUE TITLE
No able to connect to the Server

### ISSUE THREAD

**Issue by AmAnVeRmA3301** [serganch/ideals#47]
When using **./idea.sh** **lsp-server** **tcp** VsCode is not connecting to the server and when I did **nmap** scan there is no ports opend where the server client should connect to

Even the STDIO mode is also not working for me getting **Header** **mode** **must** **provide** **a** **content** **length** **properly**

And in **TCP** mode getting only written **Activation** **time** : 278ms

**Comment by AmAnVeRmA3301** [comment]
TCP problem is solved but still getting error using STDIO method

**Comment by serganch** [comment]
Currently vscode extension requires environment variables to be set:

in STDIO mode:
- `IDEALS_IJ_PATH` - path to IDEA executable. The exact executable, not just the IDEA root directory.

in TCP mode:
- `IDEALS_TRANSPORT` - must be set to `TCP`
- `IDEALS_TCP_PORT` - port number (8989 by default)

We'll add this to the readme. Sorry for inconvenience.

**Comment by AmAnVeRmA3301** [comment]
Thanks
