### ISSUE TITLE
Server Plugin is not installing on EAP build 2022.3

### ISSUE THREAD

**Issue by AmAnVeRmA3301** [serganch/ideals#48]
While installing server Plugin on **EAP** **IDEA** **2022.3** its showing error that plugin only supports 222 or older

**Comment by serganch** [comment]
We don't test the plugin with early EAPs since they are usually not very stable. However, if you want to try it, you can change the restriction in `build.gradle.kts`. Just replace `untilBuild.set("222.*")` with `untilBuild.set("223.*")` in line 90 and rebuild the plugin.
